### ISSUE TITLE
成功搭建了，但没有反应

### ISSUE THREAD

**Issue by AndoKaguya** [hobk/chatgpt-telebot#10]
一顿操作下来，启动也成功了，反复检查env填写也没有问题，请问该怎么办呢
![QQ截图20230208013443](https://user-images.githubusercontent.com/53990829/217321443-84f4a65e-222b-4566-b7d1-0131a0afa46e.png)

**Comment by AndoKaguya** [comment]
看了一下日志，才发现我机器好像有问题

at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
/root/chatgpt/chatgpt-telebot/index.js:1
import * as dotenv from 'dotenv'
       ^

SyntaxError: Unexpected token *
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2023-02-08T01:40:47: { Error: Cannot find module '/root/chatgpt/chatgpt-telebot/index.js'
2023-02-08T01:40:47:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2023-02-08T01:40:47:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2023-02-08T01:40:47:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2023-02-08T01:40:47:     at Module._compile (internal/modules/cjs/loader.js:778:30)
2023-02-08T01:40:47:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2023-02-08T01:40:47:     at Module.load (internal/modules/cjs/loader.js:653:32)
2023-02-08T01:40:47:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2023-02-08T01:40:47:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2023-02-08T01:40:47:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2023-02-08T01:40:47:     at startup (internal/bootstrap/node.js:283:19) code: 'MODULE_NOT_FOUND' }
2023-02-08T01:40:48: { Error: Cannot find module '/root/chatgpt/chatgpt-telebot/index.js'
2023-02-08T01:40:48:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2023-02-08T01:40:48:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2023-02-08T01:40:48:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2023-02-08T01:40:48:     at Module._compile (internal/modules/cjs/loader.js:778:30)
2023-02-08T01:40:48:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2023-02-08T01:40:48:     at Module.load (internal/modules/cjs/loader.js:653:32)
2023-02-08T01:40:48:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2023-02-08T01:40:48:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2023-02-08T01:40:48:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2023-02-08T01:40:48:     at startup (internal/bootstrap/node.js:283:19) code: 'MODULE_NOT_FOUND' }
2023-02-08T01:40:48: { Error: Cannot find module '/root/chatgpt/chatgpt-telebot/index.js'
2023-02-08T01:40:48:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2023-02-08T01:40:48:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2023-02-08T01:40:48:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2023-02-08T01:40:48:     at Module._compile (internal/modules/cjs/loader.js:778:30)
2023-02-08T01:40:48:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2023-02-08T01:40:48:     at Module.load (internal/modules/cjs/loader.js:653:32)
2023-02-08T01:40:48:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2023-02-08T01:40:48:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2023-02-08T01:40:48:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2023-02-08T01:40:48:     at startup (internal/bootstrap/node.js:283:19) code: 'MODULE_NOT_FOUND' }
2023-02-08T01:40:49: { Error: Cannot find module '/root/chatgpt/chatgpt-telebot/index.js'
2023-02-08T01:40:49:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2023-02-08T01:40:49:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2023-02-08T01:40:49:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2023-02-08T01:40:49:     at Module._compile (internal/modules/cjs/loader.js:778:30)
2023-02-08T01:40:49:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2023-02-08T01:40:49:     at Module.load (internal/modules/cjs/loader.js:653:32)
2023-02-08T01:40:49:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2023-02-08T01:40:49:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2023-02-08T01:40:49:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2023-02-08T01:40:49:     at startup (internal/bootstrap/node.js:283:19) code: 'MODULE_NOT_FOUND' }
2023-02-08T01:40:49: { Error: Cannot find module '/root/chatgpt/chatgpt-telebot/index.js'
2023-02-08T01:40:49:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2023-02-08T01:40:49:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2023-02-08T01:40:49:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2023-02-08T01:40:49:     at Module._compile (internal/modules/cjs/loader.js:778:30)
2023-02-08T01:40:49:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2023-02-08T01:40:49:     at Module.load (internal/modules/cjs/loader.js:653:32)
2023-02-08T01:40:49:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2023-02-08T01:40:49:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2023-02-08T01:40:49:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2023-02-08T01:40:49:     at startup (internal/bootstrap/node.js:283:19) code: 'MODULE_NOT_FOUND' }
2023-02-08T01:40:50: { Error: Cannot find module '/root/chatgpt/chatgpt-telebot/index.js'
2023-02-08T01:40:50:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2023-02-08T01:40:50:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2023-02-08T01:40:50:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2023-02-08T01:40:50:     at Module._compile (internal/modules/cjs/loader.js:778:30)
2023-02-08T01:40:50:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2023-02-08T01:40:50:     at Module.load (internal/modules/cjs/loader.js:653:32)
2023-02-08T01:40:50:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2023-02-08T01:40:50:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2023-02-08T01:40:50:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2023-02-08T01:40:50:     at startup (internal/bootstrap/node.js:283:19) code: 'MODULE_NOT_FOUND' }
2023-02-08T01:40:50: { Error: Cannot find module '/root/chatgpt/chatgpt-telebot/index.js'
2023-02-08T01:40:50:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2023-02-08T01:40:50:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2023-02-08T01:40:50:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2023-02-08T01:40:50:     at Module._compile (internal/modules/cjs/loader.js:778:30)
2023-02-08T01:40:50:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2023-02-08T01:40:50:     at Module.load (internal/modules/cjs/loader.js:653:32)
2023-02-08T01:40:50:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2023-02-08T01:40:50:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2023-02-08T01:40:50:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2023-02-08T01:40:50:     at startup (internal/bootstrap/node.js:283:19) code: 'MODULE_NOT_FOUND' }
2023-02-08T01:40:51: { Error: Cannot find module '/root/chatgpt/chatgpt-telebot/index.js'
2023-02-08T01:40:51:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2023-02-08T01:40:51:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2023-02-08T01:40:51:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2023-02-08T01:40:51:     at Module._compile (internal/modules/cjs/loader.js:778:30)
2023-02-08T01:40:51:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2023-02-08T01:40:51:     at Module.load (internal/modules/cjs/loader.js:653:32)
2023-02-08T01:40:51:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2023-02-08T01:40:51:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2023-02-08T01:40:51:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2023-02-08T01:40:51:     at startup (internal/bootstrap/node.js:283:19) code: 'MODULE_NOT_FOUND' }
2023-02-08T01:40:51: { Error: Cannot find module '/root/chatgpt/chatgpt-telebot/index.js'
2023-02-08T01:40:51:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2023-02-08T01:40:51:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2023-02-08T01:40:51:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2023-02-08T01:40:51:     at Module._compile (internal/modules/cjs/loader.js:778:30)
2023-02-08T01:40:51:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2023-02-08T01:40:51:     at Module.load (internal/modules/cjs/loader.js:653:32)
2023-02-08T01:40:51:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2023-02-08T01:40:51:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2023-02-08T01:40:51:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2023-02-08T01:40:51:     at startup (internal/bootstrap/node.js:283:19) code: 'MODULE_NOT_FOUND' }
2023-02-08T01:40:52: { Error: Cannot find module '/root/chatgpt/chatgpt-telebot/index.js'
2023-02-08T01:40:52:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2023-02-08T01:40:52:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2023-02-08T01:40:52:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2023-02-08T01:40:52:     at Module._compile (internal/modules/cjs/loader.js:778:30)
2023-02-08T01:40:52:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2023-02-08T01:40:52:     at Module.load (internal/modules/cjs/loader.js:653:32)
2023-02-08T01:40:52:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2023-02-08T01:40:52:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2023-02-08T01:40:52:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2023-02-08T01:40:52:     at startup (internal/bootstrap/node.js:283:19) code: 'MODULE_NOT_FOUND' }
2023-02-08T01:40:53: { Error: Cannot find module '/root/chatgpt/chatgpt-telebot/index.js'
2023-02-08T01:40:53:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2023-02-08T01:40:53:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2023-02-08T01:40:53:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2023-02-08T01:40:53:     at Module._compile (internal/modules/cjs/loader.js:778:30)
2023-02-08T01:40:53:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2023-02-08T01:40:53:     at Module.load (internal/modules/cjs/loader.js:653:32)
2023-02-08T01:40:53:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2023-02-08T01:40:53:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2023-02-08T01:40:53:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2023-02-08T01:40:53:     at startup (internal/bootstrap/node.js:283:19) code: 'MODULE_NOT_FOUND' }
2023-02-08T01:40:53: { Error: Cannot find module '/root/chatgpt/chatgpt-telebot/index.js'
2023-02-08T01:40:53:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2023-02-08T01:40:53:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2023-02-08T01:40:53:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2023-02-08T01:40:53:     at Module._compile (internal/modules/cjs/loader.js:778:30)
2023-02-08T01:40:53:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2023-02-08T01:40:53:     at Module.load (internal/modules/cjs/loader.js:653:32)
2023-02-08T01:40:53:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2023-02-08T01:40:53:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2023-02-08T01:40:53:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2023-02-08T01:40:53:     at startup (internal/bootstrap/node.js:283:19) code: 'MODULE_NOT_FOUND' }
2023-02-08T01:40:54: { Error: Cannot find module '/root/chatgpt/chatgpt-telebot/index.js'
2023-02-08T01:40:54:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2023-02-08T01:40:54:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2023-02-08T01:40:54:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2023-02-08T01:40:54:     at Module._compile (internal/modules/cjs/loader.js:778:30)
2023-02-08T01:40:54:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2023-02-08T01:40:54:     at Module.load (internal/modules/cjs/loader.js:653:32)
2023-02-08T01:40:54:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2023-02-08T01:40:54:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2023-02-08T01:40:54:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2023-02-08T01:40:54:     at startup (internal/bootstrap/node.js:283:19) code: 'MODULE_NOT_FOUND' }
2023-02-08T01:40:54: { Error: Cannot find module '/root/chatgpt/chatgpt-telebot/index.js'
2023-02-08T01:40:54:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2023-02-08T01:40:54:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2023-02-08T01:40:54:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2023-02-08T01:40:54:     at Module._compile (internal/modules/cjs/loader.js:778:30)
2023-02-08T01:40:54:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2023-02-08T01:40:54:     at Module.load (internal/modules/cjs/loader.js:653:32)
2023-02-08T01:40:54:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2023-02-08T01:40:54:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2023-02-08T01:40:54:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2023-02-08T01:40:54:     at startup (internal/bootstrap/node.js:283:19) code: 'MODULE_NOT_FOUND' }
2023-02-08T01:40:55: { Error: Cannot find module '/root/chatgpt/chatgpt-telebot/index.js'
2023-02-08T01:40:55:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2023-02-08T01:40:55:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2023-02-08T01:40:55:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2023-02-08T01:40:55:     at Module._compile (internal/modules/cjs/loader.js:778:30)
2023-02-08T01:40:55:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2023-02-08T01:40:55:     at Module.load (internal/modules/cjs/loader.js:653:32)
2023-02-08T01:40:55:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2023-02-08T01:40:55:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2023-02-08T01:40:55:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2023-02-08T01:40:55:     at startup (internal/bootstrap/node.js:283:19) code: 'MODULE_NOT_FOUND' }
2023-02-08T01:40:55: { Error: Cannot find module '/root/chatgpt/chatgpt-telebot/index.js'
2023-02-08T01:40:55:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2023-02-08T01:40:55:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2023-02-08T01:40:55:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2023-02-08T01:40:55:     at Module._compile (internal/modules/cjs/loader.js:778:30)
2023-02-08T01:40:55:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2023-02-08T01:40:55:     at Module.load (internal/modules/cjs/loader.js:653:32)
2023-02-08T01:40:55:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2023-02-08T01:40:55:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2023-02-08T01:40:55:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2023-02-08T01:40:55:     at startup (internal/bootstrap/node.js:283:19) code: 'MODULE_NOT_FOUND' }
