### ISSUE TITLE
小白求助：Cannot find package 'dotenv' imported 

### ISSUE THREAD

**Issue by LunarAurora666** [hobk/chatgpt-telebot#9]
node index.js 报错如下：
node:internal/errors:491
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'dotenv' imported from index.js
[90m    at new NodeError (node:internal/errors:400:5)[39m
[90m    at packageResolve (node:internal/modules/esm/resolve:889:9)[39m
[90m    at moduleResolve (node:internal/modules/esm/resolve:938:20)[39m
[90m    at defaultResolve (node:internal/modules/esm/resolve:1153:11)[39m
[90m    at nextResolve (node:internal/modules/esm/loader:163:28)[39m
[90m    at ESMLoader.resolve (node:internal/modules/esm/loader:842:30)[39m
[90m    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)[39m
[90m    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)[39m
[90m    at link (node:internal/modules/esm/module_job:76:36)[39m {
  code: [32m'ERR_MODULE_NOT_FOUND'[39m

**Comment by hobk** [comment]
重新安装一下，npm install

**Comment by LunarAurora666** [comment]
OK了，这次报错，都已经填入对应的token 和APIkey了：
2023/2/7 18:54:24 --Bot has been started...
error: [polling_error] {"code":"EFATAL","message":"EFATAL: Telegram Bot Token not provided!"}
file:///D:/Personal/chatgptbot/chatgpt-telebot-master/node_modules/chatgpt/build/index.js:115
      throw new Error("ChatGPT invalid apiKey");
            ^

Error: ChatGPT invalid apiKey
    at new ChatGPTAPI (file:///D:/Personal/chatgptbot/chatgpt-telebot-master/node_modules/chatgpt/build/index.js:115:13)
    at file:///D:/Personal/chatgptbot/chatgpt-telebot-master/index.js:12:13
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.13.0

**Comment by LunarAurora666** [comment]
> 重新安装一下，npm install

可以修改调用模型参数么？
